apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
  namespace: fcg
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__Username: "guest"
  Mongo__Database: "fcg_payments"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: fcg-payments-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: payments-api-config
          env:
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: RABBITMQ_PASSWORD
            - name: Mongo__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: Mongo__ConnectionString
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: payments-api-service
  namespace: fcg
spec:
  selector:
    app: payments-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
