apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-postgres-pvc
  namespace: fcg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-database
  namespace: fcg

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kong-database

  template:
    metadata:
      labels:
        app: kong-database

    spec:
      containers:

        - name: kong-postgres
          image: postgres:16-alpine

          ports:
            - containerPort: 5432

          env:

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: KONG_POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: KONG_POSTGRES_PASSWORD

            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: platform-secrets
                  key: KONG_POSTGRES_DB

          volumeMounts:

            - name: kong-postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:

        - name: kong-postgres-data
          persistentVolumeClaim:
            claimName: kong-postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: kong-database-service
  namespace: fcg

spec:

  selector:
    app: kong-database

  ports:

    - port: 5432
      targetPort: 5432

  type: ClusterIP